# Generated by Django 4.1.7 on 2023-03-14 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JuliusPort', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'verbose_name': 'Blog', 'verbose_name_plural': 'Blogs'},
        ),
        migrations.AlterModelOptions(
            name='contactme',
            options={'verbose_name': 'Contact', 'verbose_name_plural': 'Contacts'},
        ),
    ]
