# Generated by Django 4.1.7 on 2023-03-14 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JuliusPort', '0002_alter_blog_options_alter_contactme_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blog_head',
            field=models.CharField(blank=True, max_length=900, null=True),
        ),
    ]
